name: bloc_dev_tools
description: The goal of this package is to provide developer tools to make debugging and developing easier. Built to be used with the bloc package.
version: 0.1.0
author: felix.angelov <felangelov@gmail.com>
homepage: https://github.com/felangel/bloc/tree/master/packages/bloc_dev_tools

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  bloc:
    path: ../bloc/
  web_socket_channel: 1.0.9
  uuid: 1.0.3

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  test_coverage: ^0.2.0
  mockito: ^4.0.0
